image: Visual Studio 2017

branches:
  only:
  - master

build_script:
  - msbuild.exe src\ApiApprover.sln /t:restore,build /p:Configuration=Release

test_script:
  - dotnet test src\PublicApiGeneratorTests -c Release --no-restore --no-build

artifacts:
  - path: '**\*.nupkg'
