on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '**'
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
        sdk: ["6.0.100", "6.0.302", "6.0.303", "6.0.400"]
    name: ${{ matrix.runs-on }}-${{ matrix.sdk }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Setup .NET Core 3.1 SDK # should always be installed for 3.1 runtime
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.422
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.sdk }}
    - run: dotnet --info
    - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
    - if: contains(matrix.runs-on, 'windows')
      run: ./build.cmd
    - if: contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
    - uses: actions/upload-artifact@master
      with:
        name: nugets
        path: nugets/
