on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '**'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
      - name: Install dependencies
        working-directory: src
        run: dotnet restore
      - name: Build solution [Release]
        working-directory: src
        run: dotnet build --no-restore -c Release
      - name: Build solution [Debug]
        working-directory: src
        run: dotnet build --no-restore -c Debug
      - name: Test solution [Debug]
        working-directory: src
        run: dotnet test --no-restore --no-build
      - name: Publish Tool [Release]
        working-directory: src
        run: |
          dotnet publish PublicApiGenerator.Tool/PublicApiGenerator.Tool.csproj --no-restore --no-build -c Release -f netcoreapp2.1 &&
          dotnet publish PublicApiGenerator.Tool/PublicApiGenerator.Tool.csproj --no-restore --no-build -c Release -f net7
      - name: Pack solution [Release]
        working-directory: src
        run: dotnet pack --no-restore --no-build -c Release -o out
      - name: Upload Nuget packages as workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Nuget packages
          path: |
            src/out/*
